project:
  type: website

website:
  title: "O Meu Website"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Currículo"
        href: curriculum.qmd
      - text: "Projetos" 
        href: projetos.qmd
      - text: "Contacto"
        href: contacto.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



